feat(WEBRTC-1608)
team-telnyx/telnyx-meet pull request #61
Opened 2022-03-24 20:08 UTC by DeividVeloso

2022-03-25 12:38 UTC, arghav commented
@DeividVeloso could you please fix the merge conflict?

2022-03-25 12:48 UTC, muriware approved these changes
Functional review; it LGTM!

2022-03-28 11:30 UTC, arghav requested changes

2022-03-28 11:30 UTC, arghav commented on pages/rooms/index.tsx
> +  const unReadMessages = useRef<TelnyxRoom['messages'] | null>(null);
```suggestion
  const unreadMessages = useRef<TelnyxRoom['messages'] | null>(null);
```

2022-03-28 11:30 UTC, arghav commented on pages/rooms/index.tsx
> +          unReadMessages,
```suggestion
          unreadMessages,
```

2022-06-06 02:07 UTC, muriware approved these changes
LGTM! I left a suggestion.

2022-06-06 12:18 UTC, DeividVeloso commented on components/RoomControls.tsx
> +      return false;
Sure!!

2022-06-06 12:29 UTC, merged