feat(WEBRTC-1615):
team-telnyx/telnyx-meet pull request #64
Opened 2022-03-28 17:12 UTC by DeividVeloso

2022-03-28 17:16 UTC, DeividVeloso commented on components/Feeds.tsx
> +  useEffect(() => {
This block of code should be removed before merge

2022-03-28 17:17 UTC, DeividVeloso commented on components/Room.tsx
> +              <button onClick={() => room.disableNetworkMetrics()}>STOP Metrics</button>
This button should be removed before merge

2022-03-30 13:48 UTC, DeividVeloso commented on components/Room.tsx
> +            <div>
Should remove before merge

2022-03-30 14:29 UTC, arghav requested changes

2022-03-30 14:29 UTC, arghav commented on hooks/room.ts
> +import { NetworkMetrics } from '@telnyx/video/lib/metrics/interfaces';
Let's export this from `@telnyx/video`

2022-03-30 14:29 UTC, arghav commented on hooks/room.ts
> +        roomRef.current.on('network_metrics_changed', (networkMetrics) => {
Maybe we can rename this event to `network_metrics_report`?

2022-03-30 14:29 UTC, arghav commented on components/WebRTCStats.tsx
> +  z-index: 5;
Let's set this back to `1`

2022-03-30 14:29 UTC, arghav commented on components/Room.tsx
> +
Prettier needs to be configured to format this automatically

2022-03-30 14:29 UTC, arghav commented on components/Room.tsx
>              <Feeds
Let's move this to `useRoom` hook

2022-03-30 14:29 UTC, arghav commented on components/Feed.tsx
> +  networkMetrics: TelnyxRoom['networkMetrics']
Let's remove this and use the context

2022-04-04 23:21 UTC, arghav approved these changes
LGTM! 🎉

2022-04-05 06:58 UTC, muriware approved these changes
LGTM!

2022-04-06 11:57 UTC, merged